<a href="https://colab.research.google.com/github/bhuyash/Bhuyash.MPGI/blob/main/Matrix_Opertaions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

ar_row_size=int(input("Enter Row size of array 1:"))
ar_col_size=int(input("Enter Column size of array 1:"))
ar1_row_size=int(input("Enter Row size of array 2:"))
ar1_col_size=int(input("Enter Column size of array 2:"))
num=input(f"enter {ar_col_size*ar_row_size} elements of array 1 Seprated by space:")
num1=input(f"enter {ar1_col_size*ar1_row_size} elements of array 2 Seprated by space:")
ar1=np.array(list(map(float,num.split()))).reshape(ar_row_size,ar_col_size)
ar2=np.array(list(map(float,num1.split()))).reshape(ar1_row_size,ar1_col_size)

def addition(ar1,ar2):
  if ar1.shape!=ar2.shape:
    print("Matrices should be of same order")
  else:
    return ar1+ar2
def substraction(ar1,ar2):
  if ar1.shape!=ar2.shape:
    print("Matrices should be of same order")
  else:
    return ar1-ar2
def multiplication(ar1,ar2):
  if ar_col_size!=ar1_row_size:
    print("First matrix column size shuld be equal to second matrix row size")
  else:
    return ar1@ar2

def Transpose(ar1,ar2):
  print("Transpose of first matrix:",ar1.T)
  print("\nTranspose of second matrix:",ar2.T)

def determinant(ar1,ar2):
  if ar_row_size==ar_col_size:
    print("Determinant of Matrix 1:",np.linalg.det(ar1))
  else:
    print("Matrix 1 is not a square matrix")

  if ar1_row_size==ar1_col_size:
    print("Determinant of Matrix 2:",np.linalg.det(ar2))
  else:
    print("Matrix 2 is not a square matrix")

def Inverse(ar1,ar2):
  if np.linalg.det(ar1)!=0:
    print("Inverse of matrix 1:",np.linalg.inv(ar1))
  else:
    print("Inverse cant be found of matrix 1")

  if np.linalg.det(ar2)!=0:
    print("Inverse of matrix 2:",np.linalg.inv(ar2))
  else:
    print("Inverse cant be found of matrix 2")

ch="yes"
while(ch.lower()=="yes"):
  print("\t\t\t #### Main Menu #### \t\t\t\t")
  print("1.Addition\n2.Substraction\n3.Multiplication\n4.Transpose\n5.Determinant\n6.Inverse")
  choice=int(input("Enter your choice:"))
  if choice==1:
    print("Addition of two matrix is:",addition(ar1,ar2))
  elif choice==2:
    print("Substraction of two matrix is:",substraction(ar1,ar2))
  elif choice==3:
    print("Multiplication of two matrix is:",multiplication(ar1,ar2))
  elif choice==4:
    Transpose(ar1,ar2)
  elif choice==5:
    determinant(ar1,ar2)
  elif choice==6:
    Inverse(ar1,ar2)
  else:
    print("Invalid choice")
  ch=input("Do you want to continue(yes/no):")




Enter Row size of array 1:3
Enter Column size of array 1:3
Enter Row size of array 2:3
Enter Column size of array 2:3
enter 9 elements of array 1 Seprated by space:1 2 3 4 5 6 7 8 9
enter 9 elements of array 2 Seprated by space:9 8 7 6 5 4 3 2 1
			 #### Main Menu #### 				
1.Addition
2.Substraction
3.Multiplication
4.Transpose
5.Determinant
6.Inverse
Enter your choice:1
Addition of two matrix is: [[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
Do you want to continue(yes/no):yes
			 #### Main Menu #### 				
1.Addition
2.Substraction
3.Multiplication
4.Transpose
5.Determinant
6.Inverse
Enter your choice:2
Substraction of two matrix is: [[-8. -6. -4.]
 [-2.  0.  2.]
 [ 4.  6.  8.]]
